-- Real Estate Extensions for C.A.B Company Ltd.
-- Optimized for InsForge (PostgreSQL)

CREATE TABLE IF NOT EXISTS properties (
  id TEXT PRIMARY KEY,
  name TEXT NOT NULL,
  ref_code TEXT NOT NULL UNIQUE,
  category TEXT NOT NULL DEFAULT 'residential', -- 'residential', 'commercial', 'industrial', 'land'
  type TEXT NOT NULL DEFAULT 'villas', -- 'villas', 'apartments', 'offices', 'warehouses', 'agricultural', 'investment'
  description TEXT NOT NULL,
  price NUMERIC NOT NULL,
  status TEXT NOT NULL DEFAULT 'Available', -- 'Available', 'Sold', 'Rented', 'Archived', 'Scheduled', 'Published'
  location TEXT NOT NULL,
  city TEXT NOT NULL DEFAULT 'Accra',
  district TEXT NOT NULL DEFAULT 'Airport Residential Area',
  region TEXT NOT NULL DEFAULT 'Greater Accra',
  amenities JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of amenities
  bedrooms INTEGER DEFAULT 0,
  bathrooms INTEGER DEFAULT 0,
  parking INTEGER DEFAULT 0,
  land_size TEXT, -- e.g. '0.5 Acres'
  building_size TEXT, -- e.g. '450 sqm'
  image_url TEXT NOT NULL, -- Hero image
  gallery JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of image URLs
  video_url TEXT, -- Video tour URL
  floor_plans JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of floor plans
  brochure_url TEXT, -- Download brochure link
  virtual_tour_url TEXT, -- Virtual tour URL
  nearby_schools JSONB NOT NULL DEFAULT '[]'::jsonb,
  nearby_hospitals JSONB NOT NULL DEFAULT '[]'::jsonb,
  nearby_roads JSONB NOT NULL DEFAULT '[]'::jsonb,
  agent_name TEXT DEFAULT 'Charles Boateng',
  agent_phone TEXT DEFAULT '+233 54 221 0099',
  agent_email TEXT DEFAULT 'realestate@cabcompanyltd.com',
  is_featured BOOLEAN NOT NULL DEFAULT false,
  publish_schedule TIMESTAMP WITH TIME ZONE,
  seo_title TEXT,
  seo_description TEXT,
  seo_keywords TEXT,
  reviews JSONB NOT NULL DEFAULT '[]'::jsonb, -- Array of reviews
  analytics JSONB NOT NULL DEFAULT '{"views": 150, "inquiries": 12}'::jsonb,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS property_inquiries (
  id TEXT PRIMARY KEY,
  property_id TEXT NOT NULL,
  property_name TEXT NOT NULL,
  name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT NOT NULL,
  type TEXT NOT NULL, -- 'Inspection', 'Request', 'Contact'
  preferred_date TEXT,
  preferred_time TEXT,
  message TEXT NOT NULL,
  status TEXT NOT NULL DEFAULT 'Pending', -- 'Pending', 'Contacted', 'Completed'
  created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);

-- Seed properties
INSERT INTO properties (
  id, name, ref_code, category, type, description, price, status, location, city, district, region, 
  amenities, bedrooms, bathrooms, parking, land_size, building_size, image_url, gallery, video_url, 
  floor_plans, brochure_url, virtual_tour_url, nearby_schools, nearby_hospitals, nearby_roads, 
  agent_name, agent_phone, agent_email, is_featured, seo_title, seo_description, seo_keywords
) VALUES
  (
    'prop-villa-1', 
    'The Oyster Bay Luxury Eco-Villa', 
    'CAB-RE-101', 
    'residential', 
    'villas', 
    'Designed by international award-winning architects, The Oyster Bay Luxury Eco-Villa represents the pinnacle of sustainable modern living in Accra. This pristine residence features full solar integrated backup, smart automation, thermodynamic cooling systems, and an organic garden watered entirely by a custom greywater loop engineered by C.A.B Water Services.', 
    1450000, 
    'Available', 
    'Airport Residential Area, Accra', 
    'Accra', 
    'Airport Residential Area', 
    'Greater Accra', 
    '["Integrated Solar Power (15kW)", "Smart Automation System", "Saltwater Swimming Pool", "CAB Water Purification System", "Private Gym", "24/7 Concierge Security", "Wine Cellar", "Gourmet Kitchen"]'::jsonb, 
    5, 
    6, 
    4, 
    '0.6 Acres', 
    '620 sqm', 
    'https://images.unsplash.com/photo-1512917774080-9991f1c4c750?auto=format&fit=crop&q=80&w=800', 
    '["https://images.unsplash.com/photo-1613977257363-707ba9348227?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1613490493576-7fde63acd811?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1513694203232-719a280e022f?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    'https://www.youtube.com/watch?v=dQw4w9WgXcQ', 
    '["https://images.unsplash.com/photo-1580587771525-78b9dba3b914?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '#', 
    '#', 
    '["Lincoln International School (5 mins)", "Ghana International School (10 mins)"]'::jsonb, 
    '["Nyaho Medical Centre (4 mins)", "Airport Clinic (6 mins)"]'::jsonb, 
    '["Liberation Road (2 mins)", "Giffard Road (5 mins)"]'::jsonb, 
    'Charles Boateng', 
    '+233 54 221 0099', 
    'realestate@cabcompanyltd.com', 
    true, 
    'Oyster Bay Luxury Eco-Villa Airport Residential Area Accra', 
    'Pristine luxury 5-bedroom eco-villa for sale in Accra, Airport Residential Area. Fully solar-backed and purified water systems.', 
    'luxury villa accra, buy home accra, oyster bay cab, airport residential property'
  ),
  (
    'prop-office-2', 
    'CAB Meridian Corporate Plaza', 
    'CAB-RE-202', 
    'commercial', 
    'offices', 
    'State-of-the-art office spaces available for corporate headquarters, multi-national offices, and tech hubs. Designed for ultimate structural safety, energy-efficiency, and productivity. Features low-E double-glazed glass curtain walls, high-efficiency VRF climate systems, and a multi-barrier RO water filtration loop.', 
    3200000, 
    'Available', 
    'Liberation Road, Airport City, Accra', 
    'Accra', 
    'Airport City', 
    'Greater Accra', 
    '["Fiber Optic Internet Backbone", "Centralized HVAC with Hepa filters", "Double-Glazed Energy Saving Glass", "High Capacity Underground Water Reservoir", "Automatic Fire Sprinkler System", "Secure Underground Parking (120 vehicles)", "Smart Access Card System"]'::jsonb, 
    0, 
    12, 
    120, 
    '1.2 Acres', 
    '3400 sqm', 
    'https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800', 
    '["https://images.unsplash.com/photo-1497366216548-37526070297c?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1497215728101-856f4ea42174?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '', 
    '["https://images.unsplash.com/photo-1504917595217-d4dc5ebe6122?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '#', 
    '#', 
    '["Accra College of Medicine (8 mins)"]'::jsonb, 
    '["Airport Clinic (2 mins)", "Nyaho Medical Centre (5 mins)"]'::jsonb, 
    '["Liberation Road (0 mins)", "George Bush Highway (4 mins)"]'::jsonb, 
    'Charles Boateng', 
    '+233 54 221 0099', 
    'realestate@cabcompanyltd.com', 
    true, 
    'CAB Meridian Corporate Plaza Airport City Accra Office Building', 
    'Premium commercial office building in Airport City, Accra. Energy-efficient corporate headquarters for sale.', 
    'office space accra, commercial property airport city, cab meridian plaza, buy office building'
  ),
  (
    'prop-land-3', 
    'CAB Green-Valley Agro-Industrial Land Block', 
    'CAB-RE-303', 
    'land', 
    'agricultural', 
    'Uniquely positioned agricultural block spanning 150 acres of flat fertile land. Fully certified, graded, and cleared. It features direct proximity to water reservoirs, an on-site solar drip irrigation hub constructed by C.A.B Agro-Industries, and rich loamy soil ideal for organic exports, vegetables, and high-yield hybrid maize.', 
    450000, 
    'Available', 
    'Kasoa Plains, Central Region', 
    'Kasoa', 
    'Kasoa Plains', 
    'Central Region', 
    '["Cleared and Flat Terrain", "CAB Solar Irrigation Connection Ready", "Rich Loamy Organic Soil Base", "Deep Borehole Tap Access", "Perimeter Security Wire", "Access Road Graded"]'::jsonb, 
    0, 
    0, 
    0, 
    '150 Acres', 
    'N/A', 
    'https://images.unsplash.com/photo-1500937386664-56d1dfef3854?auto=format&fit=crop&q=80&w=800', 
    '["https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1592417817098-8f3d6eb19675?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '', 
    '[]'::jsonb, 
    '#', 
    '#', 
    '["Kasoa Agriculture Technical Institute (12 mins)"]'::jsonb, 
    '["Kasoa Poly Clinic (15 mins)"]'::jsonb, 
    '["N1 Accra-Winneba Highway (10 mins)"]'::jsonb, 
    'Charles Boateng', 
    '+233 54 221 0099', 
    'realestate@cabcompanyltd.com', 
    false, 
    'CAB Green-Valley Agro-Industrial Land Kasoa Central Region', 
    '150 Acres of premium certified agricultural land for sale in Kasoa. Ideal for large-scale farming with solar drip connections.', 
    'agricultural land ghana, farm land for sale kasoa, cab green valley, fertile land west africa'
  ),
  (
    'prop-industrial-4', 
    'Tema Industrial Hub Warehouse Complex', 
    'CAB-RE-404', 
    'industrial', 
    'warehouses', 
    'High-volume, heavy-duty warehouse complex ideal for multi-national logistics, manufacturing, and raw material storage. Engineered with reinforced steel columns, 12m clear heights, laser-leveled heavy loading floor bays, dual container docks, and an autonomous water reservoir and solar micro-grid designed and installed by C.A.B Systems.', 
    1850000, 
    'Available', 
    'Tema Free Zones Enclave, Tema', 
    'Tema', 
    'Free Zones Enclave', 
    'Greater Accra', 
    '["12m Clear Ceiling Height", "Laser-leveled Concrete Floors", "Dual Hydraulic Container Docks", "CAB Solar Micro-Grid Ready", "150,000L Fire Water Storage", "24/7 Heavy Armed Security Gate", "Industrial Weighbridge Closeby"]'::jsonb, 
    0, 
    8, 
    15, 
    '2.4 Acres', 
    '1850 sqm', 
    'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?auto=format&fit=crop&q=80&w=800', 
    '["https://images.unsplash.com/photo-1504307651254-35680f356dfd?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '', 
    '["https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '#', 
    '#', 
    '["Tema Technical Institute (8 mins)"]'::jsonb, 
    '["Tema General Hospital (12 mins)"]'::jsonb, 
    '["Tema-Akosombo Highway (3 mins)", "Tema Motorway (6 mins)"]'::jsonb, 
    'Charles Boateng', 
    '+233 54 221 0099', 
    'realestate@cabcompanyltd.com', 
    false, 
    'Tema Industrial Warehouse Complex Free Zones Accra', 
    'Premium heavy-duty industrial warehouse for sale in Tema Free Zones. Includes container docks and solar integration.', 
    'warehouse for sale tema, industrial warehouse accra, tema free zones property, cab real estate'
  ),
  (
    'prop-apt-5', 
    'The SkyRise Luxury Penthouse Suites', 
    'CAB-RE-505', 
    'residential', 
    'apartments', 
    'Commanding panoramic views of Accra skyline, the SkyRise Penthouse Suites represent ultimate sophistication. With a premium sky terrace, private dip-pool, fully furnished smart luxury interiors, absolute sound isolation, and direct pure water dispenser taps serviced by C.A.B Water Engineering.', 
    890000, 
    'Available', 
    'Cantonments, Accra', 
    'Accra', 
    'Cantonments', 
    'Greater Accra', 
    '["Sky Terrace & Private Pool", "Floor-to-ceiling panoramic windows", "24/7 backup generators", "Dedicated executive lift", "Water purification treatment on tap", "Concierge reception and VIP club lounge"]'::jsonb, 
    3, 
    3.5, 
    2, 
    'N/A', 
    '240 sqm', 
    'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?auto=format&fit=crop&q=80&w=800', 
    '["https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&q=80&w=800", "https://images.unsplash.com/photo-1560448204-e02f11c3d0e2?auto=format&fit=crop&q=80&w=800"]'::jsonb, 
    '', 
    '[]'::jsonb, 
    '#', 
    '#', 
    '["Cantonments American International School (3 mins)"]'::jsonb, 
    '["Police Hospital (6 mins)"]'::jsonb, 
    '["Giffard Road (1 min)", "Ring Road East (4 mins)"]'::jsonb, 
    'Charles Boateng', 
    '+233 54 221 0099', 
    'realestate@cabcompanyltd.com', 
    true, 
    'The SkyRise Luxury Penthouse Suites Cantonments Accra', 
    'Stunning 3-bedroom luxury penthouse suites in Cantonments, Accra. Panoramic city view, smart luxury home.', 
    'penthouse for sale cantonments, cantonments luxury apartments, buy home cantonments, skyrise suites'
  );
